### ISSUE TITLE
Comments on the capstone.rmd

### ISSUE THREAD

**Issue by frenkiboy** [BIMSBbioinfo/compgen2021Capstone#4]
Get to Know Your Data could be split into two parts:
1. Data sources
2. Data types

Data type description should also describe the format in which the data is recorded.

Drug response contains the drug response both for the cell lines and the PDX models. It should be mentioned that the AUC does not measure the same things on the cell lines and PDX samples, and that the drug response distribution on PDX and Cell lines can be markedly different, even for same drugs (that can actually be an exercise - to compare the drug response distributions between different models).

Under the Tasks part. The text which mentions the task should be more nicely formatted (bold letters for the part of the text which mentions the tasks)

**Comment by al2na** [comment]
edited accordingly
